
STARTING TRAINING: experiment 1
  0%|                                                                                         | 0/313 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/ltorres/leo/Cloud-Classification/cloud_classification/train.py", line 87, in <module>
    train(CONFIG_FILENAME,
  File "/home/ltorres/leo/Cloud-Classification/cloud_classification/train.py", line 61, in train
    model, data_logger = trainer.train()
  File "/home/ltorres/leo/Cloud-Classification/cloud_classification/src/model.py", line 58, in train
    train_loss, train_acc, train_targets, train_predictions = utils.train_model(
  File "/home/ltorres/leo/Cloud-Classification/cloud_classification/src/utils.py", line 198, in train_model
    loss = criterions["main_head"](logits_main_head)
  File "/home/ltorres/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'target'